

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."favorite_shogi_moves" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "sfenx" "text" DEFAULT ''::"text" NOT NULL,
    "move" "text" DEFAULT ''::"text" NOT NULL
);


ALTER TABLE "public"."favorite_shogi_moves" OWNER TO "postgres";


ALTER TABLE "public"."favorite_shogi_moves" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."favorite_shogi_moves_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."game_records" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "game_hash" "text" NOT NULL,
    "start_time" "text",
    "end_time" "text",
    "black_player" "text",
    "white_player" "text",
    "event" "text",
    "handicap" "text",
    "result" "text",
    "move_count" integer NOT NULL,
    "recorded_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."game_records" OWNER TO "postgres";


ALTER TABLE "public"."game_records" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."game_records_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."shogi_moves_statistics" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "sfenx" "text" DEFAULT ''::"text" NOT NULL,
    "move" "text" DEFAULT ''::"text" NOT NULL,
    "win" boolean NOT NULL,
    "lose" boolean NOT NULL,
    "timeout" boolean NOT NULL
);


ALTER TABLE "public"."shogi_moves_statistics" OWNER TO "postgres";


ALTER TABLE "public"."shogi_moves_statistics" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."shogi_moves_statistics_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."favorite_shogi_moves"
    ADD CONSTRAINT "favorite_shogi_moves_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."game_records"
    ADD CONSTRAINT "game_records_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."shogi_moves_statistics"
    ADD CONSTRAINT "shogi_moves_statistics_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_game_records_end_time" ON "public"."game_records" USING "btree" ("end_time");



CREATE INDEX "idx_game_records_hash_recorded_at" ON "public"."game_records" USING "btree" ("game_hash", "recorded_at");



CREATE INDEX "idx_game_records_players" ON "public"."game_records" USING "btree" ("black_player", "white_player");



CREATE INDEX "idx_game_records_start_time" ON "public"."game_records" USING "btree" ("start_time");



ALTER TABLE "public"."favorite_shogi_moves" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."game_records" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."shogi_moves_statistics" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."favorite_shogi_moves" TO "anon";
GRANT ALL ON TABLE "public"."favorite_shogi_moves" TO "authenticated";
GRANT ALL ON TABLE "public"."favorite_shogi_moves" TO "service_role";



GRANT ALL ON SEQUENCE "public"."favorite_shogi_moves_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."favorite_shogi_moves_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."favorite_shogi_moves_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."game_records" TO "anon";
GRANT ALL ON TABLE "public"."game_records" TO "authenticated";
GRANT ALL ON TABLE "public"."game_records" TO "service_role";



GRANT ALL ON SEQUENCE "public"."game_records_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."game_records_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."game_records_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."shogi_moves_statistics" TO "anon";
GRANT ALL ON TABLE "public"."shogi_moves_statistics" TO "authenticated";
GRANT ALL ON TABLE "public"."shogi_moves_statistics" TO "service_role";



GRANT ALL ON SEQUENCE "public"."shogi_moves_statistics_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."shogi_moves_statistics_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."shogi_moves_statistics_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
